language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION '; set testOptions in Test ++= Seq(Tests.Argument("-F"), Tests.Argument("10.0")); coverage; test'
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
