language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION '; set testOptions in Test ++= Seq(Tests.Argument("-F"), Tests.Argument("20.0")); coverage; test'
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
